# Generated by Django 5.0.6 on 2026-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_target', models.PositiveIntegerField()),
                ('protein_g', models.PositiveIntegerField()),
                ('carbs_g', models.PositiveIntegerField()),
                ('fats_g', models.PositiveIntegerField()),
                ('water_ml', models.PositiveIntegerField(default=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
