# Generated by Django 5.0.6 on 2026-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('chest_cm', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('waist_cm', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('arm_cm', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('leg_cm', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='progress/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
