# Generated by Django 5.0.6 on 2026-05-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutplanexercise',
            options={'ordering': ['day', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='workoutplanexercise',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='days_per_week',
            field=models.PositiveSmallIntegerField(choices=[(4, '4 days'), (5, '5 days'), (6, '6 days')], default=4),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='nutrition_guidance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='structure',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day number in the plan'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutplanexercise',
            unique_together={('plan', 'day', 'order')},
        ),
    ]
