# Generated by Django 5.0.6 on 2026-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('full_body', 'Full body')], max_length=20)),
                ('equipment_needed', models.CharField(blank=True, max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('calories_burn_estimate', models.PositiveIntegerField(help_text='kcal per 30 min, 70kg person')),
                ('met_value', models.DecimalField(decimal_places=2, default=4.0, help_text='Metabolic Equivalent of Task', max_digits=4)),
                ('video_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
